// posts
// 增改
export const UPDATE_POSTS_REQUESTED = "UPDATE_POSTS_REQUEST";
export const UPDATE_POSTS_SUCCEEDED = "UPDATE_POSTS_SUCCEEDED";
export const UPDATE_POSTS_REQUEST_FAILED = "UPDATE_POSTS_REQUEST_FAILED";
// 删
export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCEEDED = "DELETE_POST_SUCCEEDED";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED" 
// 查

export const UPDATE_CURRENT_READ_POST_ID = "UPDATE_CURRENT_READ_POST_ID";



// user
export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";
